development:
  adapter: postgresql
  encoding: unicode
  database: bugsoft_development
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: bugsoft_test
  pool: 5
  username: myapp
  password: password1
